accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import RegistrationView, ProfileView, UserChangeView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name="login.html"), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegistrationView.as_view(), name='register'),
    path('<int:pk>/profile/', ProfileView.as_view(), name='profile'),
    path('<int:pk>/profile/edit/', UserChangeView.as_view(), name='profile_change'),
    path('<int:pk>/profile/password-change/', UserPasswordChangeView.as_view(), name='password_change'),
]

hello/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls")),
    path('accounts/', include("accounts.urls")),
    path('webapp/', include('webapp.urls')),
    path('calculator/', include('calculator.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

from django.contrib.auth import get_user_model


class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), related_name='profile', on_delete=models.CASCADE, verbose_name='Пользователь')
    birth_date = models.DateField(null=True, blank=True, verbose_name='Дата рождения')
    avatar = models.ImageField(null=True, blank=True, upload_to='avatars', verbose_name='Аватар',)

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from accounts.models import Profile


class MyUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name', 'email']


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['birth_date', "avatar"]

accounts/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import CreateView, DetailView, UpdateView

from accounts.forms import MyUserCreationForm, UserChangeForm, ProfileChangeForm
from accounts.models import Profile

User = get_user_model()


class RegistrationView(CreateView):
    form_class = MyUserCreationForm
    template_name = "registration.html"
    model = User

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user)
        login(self.request, user)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('webapp:articles')
        return next_url


class ProfileView(LoginRequiredMixin, DetailView):
    model = User
    template_name = "user_profile.html"
    context_object_name = "user_obj"
    paginate_related_by = 3

    def get_context_data(self, **kwargs):
        articles = self.object.articles.order_by('-created_at')
        paginator = Paginator(articles, self.paginate_related_by)
        page_number = self.request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        kwargs['page_obj'] = page
        kwargs['articles'] = page.object_list
        kwargs['is_paginated'] = page.has_other_pages()
        return super().get_context_data(**kwargs)


class UserChangeView(PermissionRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'

    def has_permission(self):
        return self.request.user == self.get_object()

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
        return super().get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        response = super().form_valid(form)
        profile_form.save()
        return response

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)
        return self.render_to_response(context)

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return ProfileChangeForm(**form_kwargs)

    def get_success_url(self):
        return reverse('accounts:profile', kwargs={'pk': self.object.pk})


class UserPasswordChangeView(PasswordChangeView):
    template_name = 'user_password_change.html'

    def get_success_url(self):
        return reverse('accounts:profile', kwargs={'pk': self.request.user.pk})

accounts/templates/login.html
{% extends "base.html" %}

{% block content %}
    <h1>Вход</h1>
    {{ request.get_full_path }}
    <form action="" method="post" class="text-center w-25 ms-auto me-auto">
        {% csrf_token %}
        {% if has_error %}
            <p class="form-error">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="form-group">
            <label for="username" class="form-label">Имя пользователя:</label>
            <input class="form-control" type="text" name="username" id="username">
        </div>
        <div class="form-group">
            <label for="password" class="form-label">Пароль:</label>
            <input class="form-control" type="password" name="password" id="password">
        </div>
        {% if next_param %}
            <input type="hidden" name="next" value="{{ next_param }}">
        {% endif %}
        <button class="mt-3 btn btn-light" type="submit">Войти</button>
    </form>
{% endblock %}

accounts/templates/registration.html
{% extends "base.html" %}


{% block links %}
{% endblock %}

{% block content %}
    <h1>Рeгистрация</h1>

    <form action="" method="post">
        {% csrf_token %}
        {% include 'partial/form.html' with button_text='Зарегестрироваться' %}
    </form>
{% endblock %}

accounts/templates/user_change.html
{% extends "base.html" %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'partial/form.html' with fields_only=True %}
        {% include 'partial/form.html' with form=profile_form button_text='Редактировать' %}
    </form>
{% endblock %}

accounts/templates/user_password_change.html
{% extends 'base.html' %}

{% block content %}

    <form action="" method="post">
        {% csrf_token %}
        {% include 'partial/form.html' with button_text='Сменить пароль' %}
    </form>
{% endblock %}

accounts/templates/user_profile.html
{% extends "base.html" %}


{% block links %}
    {% if user_obj == request.user %}
        <li class="nav-item">
            <a class="nav-link" aria-current="page"
               href="{% url 'accounts:profile_change' user_obj.pk %}">Редактировать</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" aria-current="page"
               href="{% url 'accounts:password_change' user_obj.pk %}">Сменить пароль</a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="card" style="width: 18rem;">
        <img src="{{ user_obj.profile.avatar.url }}" class="card-img-top" alt="...">
        <div class="card-body">
            <p class="card-text">Ник нэйм {{ user_obj.username }}</p>
            <p class="card-text">Email {{ user_obj.email }}</p>
            <p class="card-text">Дата рождения {{ user_obj.profile.birth_date|default:'не указана' }}</p>
        </div>
    </div>
    {% include 'partial/articles_list.html' %}
{% endblock %}